default:
  tags:
      - kgr1-instance-mini

variables:
  LIB_REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kit.edu/${CI_PROJECT_NAMESPACE}/lib.git
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # CI_DEBUG_SERVICES: true
  PYTHONUNBUFFERED: true

stages:
  - build_image
  - test
  - coverage
  - docs

cache:
  paths:
    - .cache/pip

build_image:
  needs: []
  before_script: []
  stage: build_image
  tags:
    - kgr1-instance-standard
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true
      --cache-ttl=6h
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg LIB_REPO_URL=${LIB_REPO_URL}
      --build-arg BRANCH=${CI_COMMIT_BRANCH}
      --build-arg INSTALL_LIB=true
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}


pytest_mariadb:
  parallel: 8
  needs:
    - pytest
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - |
      python -c "
      import time
      import mysql.connector
      connection_available = False
      while not connection_available:
        try:
          conn = mysql.connector.connect(user='root',
            password='misp', host='db', database='mmisp-tests')
          connection_available = True
        except mysql.connector.errors.DatabaseError as e:
          print(e)
          time.sleep(3)
      conn.close()"
    - pytest --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX tests/api/routers
  services:
    - name: mariadb:11.5
      alias: db
  variables:
    MARIADB_ROOT_PASSWORD: misp
    MARIADB_DATABASE: mmisp-tests
    DATABASE_URL: "mysql+aiomysql://root:misp@db:3306/mmisp-tests"
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
    DEBUG: true


pytest:
  parallel: 8
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - ENV_FILE=.env.test.lite pytest --junitxml=report.xml --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX  --cov --cov-report= tests/api/routers
  variables:
    COVERAGE_FILE: ".coverage.${CI_NODE_INDEX}"
  artifacts:
      when: always
      paths:
        - ".coverage.*"
      reports:
        junit: report.xml

pytest_coverage_combine:
  stage: coverage
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - coverage combine
    - coverage xml
    - sed -i 's,/home/mmisp/.local/lib/python3.11/site-packages/,src/,' coverage.xml
    - sed -i 's,<source></source>,<source>./</source>,' coverage.xml
    - coverage report
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# also run pytest with sqlalchemy v2
pytest_sa2:
  needs:
    - pytest
  parallel: 8
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - pip install "sqlalchemy>=2.0"
    - ENV_FILE=.env.test.lite pytest --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX  tests/api/routers

mypy:
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - pip install "sqlalchemy>=2.0"
    - MYPYPATH=src mypy --explicit-package-bases src/mmisp/api

legacy_misp:
  tags:
      - kgr1-instance-standard
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - while [ ! -f "$MISP_READY_FILE" ]; do sleep 10; done
    - pytest tests/compatibility_tests
  services:
    - name: mariadb:11.5
      alias: db
      variables:
        HEALTHCHECK_TCP_PORT: 3306
    - name: registry.cert.kit.edu/public-gitlab-ci/misp-core:latest
      alias: misp-core
      variables:
        MYSQL_PASSWORD: misp
        MYSQL_USER: root
        DISABLE_SSL_REDIRECT: true
        HEALTHCHECK_TCP_PORT: 80
        ENABLE_DB_SETTINGS: "false"
        DEBUG: 1
    - name: valkey/valkey:7.2
      command: ["--requirepass 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ"]
      alias: redis
      variables:
        HEALTHCHECK_TCP_PORT: 6379
  variables:
    MARIADB_ROOT_PASSWORD: misp
    MARIADB_DATABASE: misp
    REDIS_PASSWORD: 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ
    DATABASE_URL: "mysql+aiomysql://root:misp@db:3306/misp"
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
    DEBUG: true
    MISP_READY_FILE: '${CI_PROJECT_DIR}/misp_ready'


create_api_spec:
  needs:
    - build_image
  stage: docs
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/api:${CI_COMMIT_SHA}
  script:
    - python -c 'import json; import mmisp.api.main; print(json.dumps(mmisp.api.main.app.openapi()))' > openapi.json
    - python -c 'import yaml; import mmisp.api.main; print(yaml.dump(mmisp.api.main.app.openapi()))' > openapi.yaml
  artifacts:
      paths:
        - "openapi.json"
        - "openapi.yaml"
  variables:
    CONNECTION_INIT: False

generate_mkdocs:
  before_script: []
  stage: docs
  needs: []
  image: registry.cert.kit.edu/public-gitlab-ci/mkdocs
  script:
    - source /root/.venv/bin/activate; PYTHONPATH=src mkdocs build
  artifacts:
    paths:
      - site
  services:
    - name: plantuml/plantuml-server
      alias: plantuml
