default:
  tags:
      - any-image-allowed

variables:
  LIB_REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kit.edu/${CI_PROJECT_NAMESPACE}/lib.git
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test

cache:
  paths:
    - .cache/pip

before_script:
  - pip install virtualenv
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -e '.[dev]'
  - if [ "$CI_PROJECT_NAMESPACE" != "kit/kit-cert/mmisp" ] || [ "$CI_COMMIT_REF_NAME" != "main" ]; then
      if git ls-remote --exit-code --heads $LIB_REPO_URL $CI_COMMIT_REF_NAME; then
        pip install --force-reinstall git+${LIB_REPO_URL}@${CI_COMMIT_REF_NAME};
      fi
    fi

pytest_mariadb:
  stage: test
  image: python:3.11
  script:
    - pytest -x tests
  services:
    - name: mariadb:latest
      alias: db
  variables:
    MARIADB_ROOT_PASSWORD: misp
    MARIADB_DATABASE: mmisp-tests
    DATABASE_URL: "mysql+aiomysql://root:misp@db:3306/mmisp-tests"
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
    DEBUG: true


pytest:
  stage: test
  image: python:3.11
  script:
    - ENV_FILE=.env.test.lite pytest --cov --cov-report term --cov-report xml:coverage.xml tests
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# also run pytest with sqlalchemy v2
pytest_sa2:
  stage: test
  image: python:3.11
  script:
    - pip install "sqlalchemy>=2.0"
    - ENV_FILE=.env.test.lite pytest tests

mypy:
  stage: test
  image: python:3.11
  script:
    - pip install "sqlalchemy>=2.0"
    - MYPYPATH=src mypy --explicit-package-bases src/mmisp/api

legacy_misp:
  stage: test
  image: curlimages/curl:latest
  before_script: []
  script:
    - "curl -v http://misp-core/"
  services:
    - name: mariadb:latest
      alias: db
    - name: hub.cert.kit.edu:5000/misp-core:latest
      alias: misp-core
      variables:
        MYSQL_PASSWORD: misp
        MYSQL_USER: root
        DISABLE_SSL_REDIRECT: true
  variables:
    MARIADB_ROOT_PASSWORD: misp
    MARIADB_DATABASE: misp
    DATABASE_URL: "mysql+aiomysql://root:misp@db:3306/misp"
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
    DEBUG: true
