---
site_name: Modern MISP API Documentation
docs_dir: docs
repo_url: https://gitlab.kit.edu/kit/kit-cert/mmisp/api
site_author: Modern MISP API Team

theme:
  name: "material"

nav:
  - index.md
  - api_package.md
  - Routers:
      - Introduction: api_routers_package.md
      - Attributes: routers/attributes.md
      - Auth Keys: routers/auth_keys.md
      - Authentication: routers/authentication.md
      - Events: routers/events.md
      - Feeds: routers/feeds.md
      - Galaxies: routers/galaxies.md
      - Galaxy Clusters: routers/galaxy_clusters.md
      - Jobs: routers/jobs.md
      - Noticelists: routers/noticelists.md
      - Objects: routers/objects.md
      - Organisations: routers/organisations.md
      - Roles: routers/roles.md
      - Servers: routers/servers.md
      - Sharing Groups: routers/sharing_groups.md
      - Sightings: routers/sightings.md
      - Statistics: routers/statistics.md
      - Tags: routers/tags.md
      - Taxonomies: routers/taxnomies.md
      - User Settings: routers/user_settings.md
      - Users: routers/users.md
      - Warninglists: routers/warninglists.md
  - Frontend Reference: /frontend/intro
  - Library Reference: /lib/introduction
  - API Reference: /api/
  - Worker Reference: /worker/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            separate_signature: true
            show_signature_annotations: true

            
  - plantuml:
      puml_url: http://plantuml:8080/
      num_workers: 4
  - build_plantuml:
      render: 'server'
      server: http://plantuml:8080/
      output_format: svg
      diagram_root: docs/plantuml
  - with-pdf:
      # See https://github.com/orzih/mkdocs-with-pdf
      cover_subtitle: Design Phase
      # NOTE: There's a zero width space in these parentheses because I couldn't make the copyright not show up otherwise.
      #       It's also possible to use custom templates with mkdocs-with-pdf, might be worth it, see github linked above.
      copyright: '​'
      toc_level: 3
