---
site_name: Modern MISP API Documentation

theme:
  name: "material"

nav:
  - index.md
  - util_package.md
  - api_package.md
  - api_routers_package.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            separate_signature: true
            show_signature_annotations: true
  - plantuml:
      puml_url: http://plantuml:8080/
      num_workers: 4
  - build_plantuml:
      render: 'server'
      server: http://plantuml:8080/
      output_format: svg
      diagram_root: docs/plantuml
  - with-pdf
